### ISSUE TITLE
NullReferenceException on loading a .dae file

### ISSUE THREAD

**Issue by RenolY2** [Sage-of-Mirrors/BMDCubed#5]
On loading a dae file which I created from a converted bmd model (to test the functionality of this converter) I'm receiving the following exception with the 0.2 release version of BMDCubed:

```
C:\Users\User\Documents\Modding\BMDCubed>BMDCubed.exe sensya.DAE

Unhandled Exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at BMDCubed.src.BMD.Skinning.SkeletonData.MakeDAESkeleton(Grendgine_Collada_Skin skin) in D:\Github\BMDCubed\BMDCubed\src\BMD\Skinning\SkeletonData.cs:line 50
   at BMDCubed.src.BMD.Skinning.SkeletonData..ctor(Grendgine_Collada scene, Grendgine_Collada_Skin skin) in D:\Github\BMDCubed\BMDCubed\src\BMD\Skinning\SkeletonData.cs:line 38
   at BMDCubed.src.BMD.Skinning.SkinningManager..ctor(Grendgine_Collada scene) in D:\Github\BMDCubed\BMDCubed\src\BMD\Skinning\SkinningManager.cs:line 20
   at BMDCubed.src.BMDManager..ctor(Grendgine_Collada scene) in D:\Github\BMDCubed\BMDCubed\src\BMDManager.cs:line 23
   at BMDCubed.Program.Main(String[] args) in D:\Github\BMDCubed\BMDCubed\Program.cs:line 53
```

I created the dae file in 3DS Max 2015, although I also tried creating the dae file with Blender on which I received the exact same exception. Is the dae file missing something? The readme of BMDCubed says static meshes with 0 bones are supported so I'm confused about this. Here is the dae file I've tried to convert: https://www.dropbox.com/s/4s5i44ucoh8jvgc/sensya.DAE?dl=0

**Comment by RenolY2** [comment]
After some talk with the developer it turns out this issue was caused by my model being made of two objects instead of just one. So if you get this exception and your model is made of two or more objects, try changing it so it's only one object.
